name: Unit-Tests

on:
  push:
  workflow_dispatch:
    inputs:
      sha:
        description: 'Hash of Commit'     
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD-HH-mm-ss
          utcOffset: "+02:00"
        
      - name: Checkout Repository
        uses: actions/checkout@v2   
        with:
          ref: '${{ github.event.inputs.sha }}'
          
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: '16.0.1'

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test
